### ISSUE TITLE
Mystery border on focus

### ISSUE THREAD

**Issue by Jar36** [ResponsiveMenu/Responsive-Menu#1]
There is a mystery border that appears around the container when I click on it. 
I haven't been successful yet using devtools to find where its coming from. 

![border](https://cloud.githubusercontent.com/assets/22058900/23341511/390544c4-fc06-11e6-817a-508b3a67de32.png)

**Comment by peter-featherstone** [comment]
Are you using Google Chrome? If so, it could be because of their accessibility features. See forum post below:

https://wordpress.org/support/topic/weird-border-around-button-only-on-chrome/
