### ISSUE TITLE
Responsive menu "accessibility" issue

### ISSUE THREAD

**Issue by nelske** [ResponsiveMenu/Responsive-Menu#8]
Currently, I'm checking a website I built (in which I used the Responsive Menu plugin) on accessibility compliance. It seems there is an issue when using the keyboard to navigate the menu.

You can actually "tab" to the open button via tab index using the tab-key, but once in the menu, tabbing should loop between the items in the opened menu and the X close button OR the menu should be able to be closed when pressing the escape button. I've attached a screen capture of the behaviour.

[No Loop trough menu.zip](https://github.com/peter-featherstone/Responsive-Menu/files/2736167/No.Loop.trough.menu.zip)

**Comment by peter-featherstone** [comment]
I've noticed this myself in the past and wasn't able to find a way to link the two items. The button is a different element from the menu itself so there is no connect between both items. If you are able to open a PR with suggested changes to solve this problem then I'm more than happy to take a look.

**Comment by nelske** [comment]
I hope I have the knowledge to do this or find someone who can :). Thank you for your swift reply.
 What about escaping the menu with ESC button, is this something that can be done? This would also work.

**Comment by nelske** [comment]
Maybe this could help with the ESC key stuff:

https://stackoverflow.com/questions/42852818/closing-menu-with-escape-key

**Comment by peter-featherstone** [comment]
Keyboard shortcuts are available in the Pro version which allow you to set the Escape key for closing the menu. 

If you are already tabbed onto the button and the menu is opened, doesn't hitting the enter key close it again?

**Comment by nelske** [comment]
If you tab until you are on the menu button it opens and closes with enter yes, but once you tab through the menu items and reach the last one, you don't go back to the close button but cycle through the entire website again before getting back to the menu open/close button.

Thanks for the comment on the pro version, I'll look into that.

**Comment by peter-featherstone** [comment]
That sounds correct behaviour to me. I assume if you reverse tab while on the menu items then you end up back at the button?

Forcing tabbing from the end of the menu to go back to the button would be like an endless loop.

**Comment by nelske** [comment]
Reverse tab works indeed.

About the endless loop; If you loop through the menu including the close button, it would be al loop you can break though. I don't know what the best practice for this is.

Seeing Shift tab works and the pro version allows ESC to close the menu, I guess this would be enough of a workaround for accessibility. You can close this issue :). Thanks for all your time.

**Comment by peter-featherstone** [comment]
You're welcome and thanks for raising it 😊
